name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Install nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          check-latest: true

      - name: Install dependencies
        run: yarn

      - name: Check code style
        run: yarn prettier --check contracts test

      - name: Compile contracts
        run: yarn run hardhat compile

      - name: Check compiled contract size
        run: yarn run hardhat size-contracts

      - name: Test
        run: yarn run hardhat test
