name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Install nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          check-latest: true

      - name: Install dependencies
        run: yarn

      - name: Compile contracts
        env:
          NODE_OPTIONS: '--max-old-space-size=6144'
        run: yarn run hardhat compile

      - name: Test
        run: yarn run hardhat test
